from typing import Optional, Protocol, Iterable

from bookstore.model.book.book_record import BookRecord


class BookRepository(Protocol):
    def get(self, book_id : int) -> Optional[BookRecord]:
        ...
    def find_all(self) -> Iterable[BookRecord]:
        ...
    def save(self, book: BookRecord) -> BookRecord:
        ...
    def delete(self, book_id: int) -> None:
        ...
    def find_all_by_title(self, title : str) -> Iterable[BookRecord]:
        ...
    def find_by_author(self, author : str) -> Iterable[BookRecord]:
        ...